### PR TITLE
Playlist strict mode, limits and fixes

### PR DESCRIPTION
**Pull request by labmonkey**
Added:
Two new options that make it safer to download playlists
- Strict Playlist mode. I tend to download videos that are part of playlists (such as `https://www.youtube.com/watch?v=VIDEO_ID&list=PLAYLIST_ID`). Unfortunately default behaviour of ytdlp in such case is to treat the link as a url and download whole playlist, even that my intention was to download just a single video.
  With the Strict Playlist mode that can be enabled/disabled by default by env variable it will now force such urls to be treated as single video url and download playlists only if directly requested (url points to `https://www.youtube.com/playlist?list=PLAYLIST_ID`). This saves user from having to manually remove the PLAYLIST_ID part from url if he wanted to achieve that. Can be also changed in the UI.
- Playlist item limit. Simply limits the amount of playlist items that can be downloaded at once. This prevents unintentional download of huge playlists or simply allows to paste playlist url and download only recent items. Can be also changed in the UI.
- `OUTPUT_TEMPLATE_PLAYLIST` for playlist specific template, mainly to download playlist entries into their own `playlist_title` subdirectory 

Fixed:
- when downloading an URL such as `https://www.youtube.com/watch?v=VIDEO_ID&list=PLAYLIST_ID` even that ytdlp was downloading a whole playlist then in the UI you could only see a single job downloading multiple videos with title same as the playlist title. It was because the `etype = 'url'` check was performed last. Now those kind of urls will be processed same as a direct playlist link and each video will be added in separate job.

### CODE REVIEW

**Comment by PikuZheng** [comment]
could this fix #382 ?

**Comment by labmonkey** [comment]
> could this fix #366 or #382 ?

I thinks those are different. I would not expect these changes to have an impact.

**Comment by alexta69** [comment]
Thanks @labmonkey !

**Comment by alexta69** [comment]
@labmonkey can you please look at #497 ? looks like the PR introduced a regression

**Comment by MattBlackOnly** [comment]
I think this should be reverted as it doesn't add anything of value and clutters the UI. 

The issues it's trying to fix are user error. 

For example, if you only want one video from a playlist, get that specific video link. 

And if you don't want to download all videos from a playlist, you can just create a new playlist with the items you do want and download that.

@alexta69

**Comment by MattBlackOnly** [comment]
And if you want to download playlists into a specific folder, you just enable DONWLOAD_DIRS_INDEXABLE and create the new folder when downloading.

**Pull request merged**
