### PR TITLE
fix: Fixed the problem of m4a audio download bit rate being too low

### PR DESCRIPTION
**Pull request by nichuanfang**

### CODE REVIEW

**Comment by PikuZheng** [comment]
I'm worried that modification will cause format selections (like mp3, opus, wav) invalid

**Comment by alexta69** [comment]
Yes, it seems like it nullifies the format selection. Also, I'm not sure why the changes in git github actions workflow are needed.

**Comment by PikuZheng** [comment]
就是你提交修改时不要直接提交，这样会把所有修改都带过来。首先要起一个基于alexta69:master的分支，然后在这个分支里修改，最后用这个分支提merge

**Comment by alexta69** [comment]
I'm sorry, I can't accept this pull request. Most of the changes in it are unrelated to the subject, for many of them I don't see any need (the github actions changes, and others), and there are comments in Chinese (I don't speak Chinese and neither do most people; open-source projects stick to English for that reason).

I'm closing this PR. If you want to fix certain functionality or implement a certain feature, please prepare a PR with only the relevant changes.

Thanks

**Pull request closed without merging**
