### PR TITLE
Add option for auto starting download.

### PR DESCRIPTION
**Pull request by nodew**
Add a new "Auto start" option to the MeTube. 
When the setting is "No", MeTube will only extract information to the list, only when clicking on the download button, it will start download select item. 
When the setting is "Yes", there's no difference than current options.

image

It's an implementation for issue #339.

### CODE REVIEW

**Comment by alexta69** [comment]
Thanks @nodew for your contribution!

**Comment by timreuscher** [comment]
Noticing a couple of things after the implementation of this (even after the default was set to Yes):

1. The Chrome extension no longer autostarts (even with the default set to Yes). For someone not monitoring Github I simply thought Metube was broken. Maybe an option in Docker for AUTOSTART with a potential value of Always that eliminates the GUI option to revert to old behavior for those who want it would be good?
2. It seems like the only way to delete something from the Downloading queue is to start the download, then delete it.

**Comment by nodew** [comment]
Hi @timreuscher I'm sorry for breaking your scenario, but I'm not aware of the use case of Chrome extension, which extension you refer to?

**Comment by timreuscher** [comment]
It's called Metube Downloader - https://chromewebstore.google.com/detail/metube-downloader/fbmkmdnlhacefjljljlbhkodfmfkijdh

Very convenient. Just click a button and it sends the page you're on to Metube.

**Comment by nodew** [comment]
@timreuscher thanks, I'll have a try.

**Comment by malikamg** [comment]
I've the same issue. previously it was working fine. two days ago all download send to metube using chrome add-on was unable to autostart

**Comment by nodew** [comment]
I made a fix, see #355

**Comment by timreuscher** [comment]
Issue seems solved by the fix. Thanks!

**Comment by PikuZheng** [comment]
Hi, I'd like to know is it an issue that I can not delete a task that didn't start automatically?

**Comment by timreuscher** [comment]
> Hi, I'd like to know is it an issue that I can not delete a task that didn't start automatically?

I seem to remember this being the case, and the workaround was to pause the download, then delete it. Might want to start a new issue on that.

**Pull request merged**
