### PR TITLE
Add iOS shortcut link

### PR DESCRIPTION
**Pull request by rithask**

### CODE REVIEW

**Comment by rithask** [comment]
#169

**Comment by alexta69** [comment]
Thanks @rithask !

**Comment by rithask** [comment]
There’s a typo in the github.com/rithask URL. I just noticed it.

**Comment by alexta69** [comment]
yes. fixed

**Comment by TheSpyder** [comment]
I was about to log a bug saying this wasn't working anymore but it was just because I'd copy/pasted the url from Safari and it had a trailing slash. I deleted that and it works.

Might be worth adding a note about that somewhere 🤔

**Pull request merged**
