### PR TITLE
Added retry button for failed download

### PR DESCRIPTION
**Pull request by Rpsl**
I added a button to retry failed download 

//cc https://github.com/alexta69/metube/issues/25

https://user-images.githubusercontent.com/265634/127456671-b4e32e51-965a-48d2-b6b1-ae41de76ad70.mov

### CODE REVIEW

**Comment by alexta69** [comment]
Thanks for the contribution!
Two questions --
1. Why did you decide to use this icon from the "solid" library instead of the "regular" library used for the other icons?
2. Perhaps it makes sense to remove it from the "failed" list when it's clicked, in other words, have this click move the entry from the bottom list to the top list, and let it move down naturally back into the bottom list once the download succeeds or fails?

**Comment by Rpsl** [comment]
> Why did you decide to use this icon from the "solid" library instead of the "regular" library used for the other icons?
Yeah, I've been thinking about it, too. I couldn't find the right icon in "[regular](https://fontawesome.com/v5.15/icons?d=gallery&p=2&s=regular&m=free)" icon set 🤷 

> have this click move the entry from the bottom list to the top list
Sounds good. I just didn't notice it. I fix that asap

**Comment by alexta69** [comment]
The icon is only available in the "Pro" version of FontAwesome for the Regular weight.. what a bummer :(

**Comment by Rpsl** [comment]
> have this click move the entry from the bottom list to the top list

[complete](https://github.com/alexta69/metube/pull/38/commits/26ae9427868a11acba31dedeab282c5f67d4c0dc)

**Pull request merged**
